//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.7.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface ExtendedClaim {
  id?: string | undefined;
  type?: string | undefined;
  value?: string | undefined;
  applicationCode?: string | undefined;
}

export interface ExtendedRoleClaim {
  roleName?: string | undefined;
  claims?: ExtendedClaim[] | undefined;
}

export interface MassLoadApplicationCreateRequestDTO {
  code?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface MassLoadApplicationGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface MassLoadApplicationResponseDTO {
  code?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface MassLoadApplicationUpdateRequestDTO {
  code?: string | undefined;
  name?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface MassfussionFunctionCreateRequestDTO {
  claimValue?: string | undefined;
  type?: string | undefined;
  description?: string | undefined;
  applicationCode?: string | undefined;
  guidId?: string;
}

export interface MassfussionFunctionGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface MassfussionFunctionResponseDTO {
  applicationCode?: string | undefined;
  applicationCodeName?: string | undefined;
  type?: string | undefined;
  claimValue?: string | undefined;
  functionDescription?: string | undefined;
}

export interface MassfussionFunctionUpdateRequestDTO {
  claimValue?: string | undefined;
  type?: string | undefined;
  description?: string | undefined;
  applicationCode?: string | undefined;
  guidId?: string;
}

export interface ModelResponseDTO {
  guidId?: string;
  modelName?: string | undefined;
  sampleModelName?: string | undefined;
  modelVersions?: ModelVersionResponseDTO[] | undefined;
}

export interface ModelVersionResponseDTO {
  value?: any | undefined;
}

export interface NotificationCreateRequestDTO {
  guid?: string;
  messageGroupGuid?: string;
  dateSent?: Date;
  dateViewed?: Date;
  dateCompleted?: Date;
  dateArchived?: Date;
  sender?: string | undefined;
  owner?: string | undefined;
  ownerStatus?: string | undefined;
  isOwner?: boolean;
  allRecipients?: string | undefined;
  originatingApp?: string | undefined;
  body?: string | undefined;
  title?: string | undefined;
  roomName?: string | undefined;
  status?: string | undefined;
  visible?: boolean;
  guidId?: string;
}

export interface NotificationGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface NotificationResponseDTO {
  value?: any | undefined;
}

export interface NotificationUpdateRequestDTO {
  guid?: string;
  messageGroupGuid?: string;
  dateSent?: Date;
  dateViewed?: Date;
  dateCompleted?: Date;
  dateArchived?: Date;
  sender?: string | undefined;
  owner?: string | undefined;
  ownerStatus?: string | undefined;
  isOwner?: boolean;
  allRecipients?: string | undefined;
  originatingApp?: string | undefined;
  body?: string | undefined;
  title?: string | undefined;
  roomName?: string | undefined;
  status?: string | undefined;
  visible?: boolean;
  guidId?: string;
}

export interface RefreshTokenCreateRequestDTO {
  id?: number;
  userId?: string | undefined;
  token?: string | undefined;
  jwtId?: string | undefined;
  isUsed?: boolean;
  isRevoked?: boolean;
  createdAt?: Date;
  expiryDate?: Date;
  guidId?: string;
}

export interface RefreshTokenGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RefreshTokenResponseDTO {
  value?: any | undefined;
}

export interface RefreshTokenUpdateRequestDTO {
  id?: number;
  userId?: string | undefined;
  token?: string | undefined;
  jwtId?: string | undefined;
  isUsed?: boolean;
  isRevoked?: boolean;
  createdAt?: Date;
  expiryDate?: Date;
  guidId?: string;
}

export interface RoomCreateRequestDTO {
  roomName?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface RoomGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RoomParticipantCreateRequestDTO {
  email?: string | undefined;
  status?: boolean;
  roomName?: string | undefined;
  guidId?: string;
}

export interface RoomParticipantGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RoomParticipantResponseDTO {
  roomName?: string | undefined;
  email?: string | undefined;
  status?: boolean;
  guidId: string;
}

export interface RoomParticipantUpdateRequestDTO {
  email?: string | undefined;
  status?: string | undefined;
  roomName?: string | undefined;
  guidId?: string;
}

export interface RoomParticipantDeleteRequestDTO {
  guidId: string;
}

export interface RoomResponseDTO {
  roomName?: string | undefined;
  guidId?: string;
  description?: string | undefined;
}

export interface RoomUpdateRequestDTO {
  roomName?: string | undefined;
  guidId?: string;
}

export interface SampleModelCreateRequestDTO {
  guidId?: string;
  sampleModelName?: string | undefined;
}

export interface SampleModelGetRequestDTO {
  sampleModelName?: string | undefined;
}

export interface SampleModelResponseDTO {
  sampleModelId?: string | undefined;
  sampleModelName?: string | undefined;
  models?: ModelResponseDTO[] | undefined;
}

export interface SampleModelUpdateRequestDTO {
  guidId?: string;
  sampleModelName?: string | undefined;
}

export interface UsersCreateRequestDTO {
  email?: string | undefined;
  password?: string | undefined;
  lastName?: string | undefined;
  firstName?: string | undefined;
  therole?: string | undefined;
  userGroup?: string | undefined;
}

export interface UsersGroupCreateRequestDTO {
  name?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface UsersGroupGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface UsersGroupResponseDTO {
  name?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface UsersGroupUpdateRequestDTO {
  name?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface UsersUpdateRequestDTO {
  email: string;
  lastName: string | null;
  firstName: string | null;
  theRole: string | null;
  userGroup: string| null;
  newValue: boolean;
  newPassword:string | null;
  actionTarget: "ChangeUserStatus" | "ChangeBarCodeStatus" | "NewBarCode"|"UserResetPassword"|"AdminResetPassword"|"ResetDetails";
  currentPassword: string | null;
}


///
export interface MassLoadApplicationResponsewtFunctionsDTO {
  code: string| undefined;
  name: string | undefined;
  description: string| undefined;
  guidId: string| undefined;
  massfussionFunctionResponse: MassfussionFunctionResponseDTOnwtFunctionsDTO[] ; 
}

///
// export type  MassLoadApplicationResponsewtFunctionsDTO= {
//   code: string ;
//   name: string ;
//   description: string ;
//   guidId: string;
//   massfussionFunctionResponse: MassLoadApplicationResponsewtFunctionsDTO[] ;
// }

// export interface MassLoadApplicationUpdateRequestDTO {
//   code?: string | undefined;
//   name?: string | undefined;
//   description?: string | undefined;
//   guidId?: string;
// }

// export interface MassfussionFunctionCreateRequestDTO {
//   claimValue?: string | undefined;
//   type?: string | undefined;
//   description?: string | undefined;
//   applicationCode?: string | undefined;
//   guidId?: string;
// }

// export interface MassfussionFunctionGetRequestDTO {
//   entityNameId?: any | undefined;
// }

// export interface MassfussionFunctionResponseDTO {
//   applicationCode?: string | undefined;
//   applicationCodeName?: string | undefined;
//   type?: string | undefined;
//   claimValue?: string | undefined;
//   functionDescription?: string | undefined;
// }

export interface MassfussionFunctionResponseDTOnwtFunctionsDTO {
  applicationCode: string | undefined;
  type: string | undefined;
  claimValue: string | undefined;
  functionDescription: string | undefined;
  guidId: string| undefined;
// export type  MassfussionFunctionResponseDTOnwtFunctionsDTO = {
//   applicationCode: string ;
//   type: string ;
//   claimValue: string ;
//   functionDescription: string ;
//   guidId: string;
// 
}