//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AddPOEventCreateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface AddPOEventResponseDTO {
    value?: any | undefined;
}

export interface AddPOEventUpdateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface ApprovalEventCreateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface ApprovalEventResponseDTO {
    value?: any | undefined;
}

export interface ApprovalEventUpdateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface CloseRequestEventCreateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface CloseRequestEventResponseDTO {
    value?: any | undefined;
}

export interface CloseRequestEventUpdateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface KanbanContainerCreateRequestDTO {
    partCode?: string | undefined;
    barcodeCode?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId?: string;
}

export interface KanbanContainerResponseDTO {
    partCode: string ;
    barcodeCode: string ;
    description: string ;
    supplier: string;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId: string;
}

export interface KanbanContainerUpdateRequestDTO {
    partCode?: string | undefined;
    barcodeCode?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId?: string;
}


export interface MaterialRequestCreateRequestDTO {

    requestDate?: Date;
    userName?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
    stage?: string | undefined;
    guidId?: string;
}

export interface MaterialRequestDetailsCreateRequestDTO {
  
    partCode?: string | undefined;
    pONumber?: string | undefined;
    notes?: string | undefined;
    
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number;
    leadTimeInDays?: number;
    guidId?: string;
}

export interface MaterialRequestDetailsResponseDTO {
    partCode: string ;
    pONumber?: string | undefined;
    notes?: string | undefined;
    
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number;
    leadTimeInDays?: number;
    guidId: string;
}

export interface MaterialRequestDetailsUpdateRequestDTO {
    materialRequestId?: string;
    partCode?: string | undefined;
    pONumber?: string | undefined;
    notes?: string | undefined;
    stage?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number;
    leadTimeInDays?: number;
    guidId?: string;
}
export interface MaterialRequestResponseDTO {
    requestDate: Date;
    userName: string ;
    description?: string | undefined;
    notes?: string | undefined;
    stage?: string | undefined;
    guidId: string;
}

export interface MaterialRequestUpdateRequestDTO {
    id?: string;
    requestDate?: Date;
    userName?: string | undefined;
    description?: string | undefined;
    notes?: string | undefined;
    stage?: string | undefined;
    guidId?: string;
}
export interface PartsTableCreateRequestDTO {
    partCode: string | undefined;
    //barcodeCode?: string | undefined;
    description: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
  //  guidId?: string;
}

export interface PartsTableResponseDTO {
    partCode?: string | undefined;
    barcodeCode?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId?: string;
}

export interface PartsTableUpdateRequestDTO {
    partCode?: string | undefined;
    barcodeCode?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId?: string;
}

/** Line item for Purchase Order */
export interface PurchaseOrderLineItem {
    itemName: string;
    description?: string | undefined;
    quantity: number;
    rate?: number | undefined;
    amount?: number | undefined;
}

//
export interface PartsSearchParams {
  SearchType: "BarCode" | "PartCode" | "Description" | "";
  BarCode:  string | null;
  PartCode:  string | null;
  Description: string | null;
 
}

export const defaultPartsSearchParamsValue: PartsSearchParams = {  
  SearchType: "",
  BarCode:  null,
  PartCode:  null,
  Description: null,
};
//Note the following DTOs are used in Purchasing Stages Kanban Card
//before i generated the dto , i may need to check them again
export interface PurchasingGetRequestByStage {
  Stage: string | undefined;
  DraftAssessment: boolean;
}
export interface PurchasingResponseDTO {
  rmaNumber: number;
  customerEmail: string;
  dateIssued?: Date;
  dateReceived?: Date;
  rmaProblemDescription: string;
  stage: string;
  salesPerson: string;
  companyName: string;
  contactName: string;
  street?: string;
  city?: string;
  province?: string;
  zipCode?: string;
  country?: string;
  phoneNumber?: string;
  notes: string;

  draftAssessment: boolean;
  salesOrderId?: string;
  guidId: string; // UUID string
}