//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

import { StageAndFields } from "../../Pages/Tracking/TheReports/Components/StageComponents/StagesModel";

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface AmplifierBoardCreateRequestDTO {
  amplifierBoardId?: number;
  brand?: string | undefined;
  name?: string | undefined;
  hasRed?: number;
  redValue?: string | undefined;
  hasGreen?: number;
  greenValue?: string | undefined;
  hasBlack?: number;
  blackValue?: string | undefined;
  hasWhite?: number;
  whiteValue?: string | undefined;
  hasShield?: number;
  shieldValue?: string | undefined;
  guidId?: string;
}

export interface AmplifierBoardGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface AmplifierBoardResponseDTO {
  value?: any | undefined;
}

export interface AmplifierBoardUpdateRequestDTO {
  amplifierBoardId?: number;
  brand?: string | undefined;
  name?: string | undefined;
  hasRed?: number;
  redValue?: string | undefined;
  hasGreen?: number;
  greenValue?: string | undefined;
  hasBlack?: number;
  blackValue?: string | undefined;
  hasWhite?: number;
  whiteValue?: string | undefined;
  hasShield?: number;
  shieldValue?: string | undefined;
  guidId?: string;
}

export interface BatchCreateRequestDTO {
  batchDetails?: BatchCreateRequestDetailsDTO;
  version?: ModelVersionResponseDTO;
}

export interface BatchCreateRequestDetailsDTO {
  batchNo?: number;
  quantity?: number;
  lastGenerateNumber?: number;
  themexPO?: string | undefined;
  machiningPO?: string | undefined;
  steelPO?: string | undefined;
  timestamp?: Date;
  modelType?: string | undefined;
  userName?: string | undefined;
  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  noOfGauges: number;
  guidId?: string;
}

export interface RequestBySerialNoOrBatchNo {
  SerialNo?: string;
  SearchBySerialNo?: boolean;
}

export interface BatchResponseDTO {
  batchNo?: number;
  modelVersionId?: number;
  modelName?: string | undefined;
  modelType?: string | undefined;
  quantity?: number;
  lastGenerateNumber?: number;
  themexPO?: string | undefined;
  machiningPO?: string | undefined;
  steelPO?: string | undefined;
  timestamp?: Date;
  modelVersionGuid?: string;
  capacity?: number;
  testCapacity?: number;
  cableLength?: number;
  processFlowGroupName?: string | undefined;
  testingMode?: string | undefined;
  maxBatchNo?: number;
  userName?: string | undefined;

  safeLoad?: number;
  ultimateLoad?: number;
  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  noOfGauges: number;
  guidId?: string;
}
//DJTO
export interface BatchUpdateRequestDTO {
  batchNo?: number;
  modelVersionId?: number;
  modelName?: string | undefined;
  quantity?: number;
  lastGenerateNumber?: number;
  themexPO?: string | undefined;
  machiningPO?: string | undefined;
  steelPO?: string | undefined;
  timestamp?: Date;
  modelVersionGuid?: string;
  capacity?: number;
  testCapacity?: number;
  cableLength?: number;
  processFlowGroupName?: string | undefined;
  testingMode?: string | undefined;
  previousQuantity?: number;
  maxBatchNo?: number;
  userName?: string | undefined;
  modelType?: string | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  noOfGauges: number;
  guidId?: string;
}

export interface DefectTypeCreateRequestDTO {
  defectName?: string | undefined;
  stage?: string | undefined;
  defectDescription?: string | undefined;
  triggerPercentage?: number;
  minBatchQuantityforTrigger?: number;
  solution?: string | undefined;
  timestamp?: Date;
  userName?: string | undefined;
  guidId?: string;
}

export interface DefectTypeGetRequestDTO {
  defectName: string | undefined;
  stage?: string | undefined;
  defectDescription?: string | undefined;
  triggerPercentage?: number;
  minBatchQuantityforTrigger?: number;
  solution?: string | undefined;
  timestamp?: Date;
  userName?: string | undefined;
  guidId?: string;
}

export interface DefectTypeResponseDTO {
  defectName: string;
  stage: string | undefined;
  defectDescription?: string | undefined;
  triggerPercentage?: number;
  minBatchQuantityforTrigger?: number;
  solution?: string | undefined;
  timestamp?: Date;
  userName?: string | undefined;
  guidId: string;
}

export interface DefectTypeUpdateRequestDTO {
  defectName?: string | undefined;
  stage?: string | undefined;
  defectDescription?: string | undefined;
  triggerPercentage?: number;
  minBatchQuantityforTrigger?: number;
  solution?: string | undefined;
  timestamp?: Date;
  userName?: string | undefined;
  guidId?: string;
}
export interface GaugeDetails {
  guageModel?: string | undefined;
  lotNo?: string | undefined;
}

export interface InventoryDetails {
  salesOrderNo?: string | undefined;
}

export interface GaugeInspectionDetails {
  //InspectionResult: number;
  defect: string | undefined;
  // GaugePassed: number | undefined;
  // GaugeFailed: number | undefined;
  //djto first make these values are compulsory to sort out the issue and make them optional later
  // GaugePassed: number ;
  // GaugeFailed: number;
}
export interface LogDetailCreateRequestDTO {
  productId?: number;
  logSummaryId?: string;
  guidId?: string;
}

export interface LogDetailGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface LogDetailResponseDTO {
  value?: any | undefined;
}

export interface LogDetailUpdateRequestDTO {
  productId?: number;
  logSummaryId?: string;
  guidId?: string;
}

export interface LogSummaryCreateRequestDTO {
  logSummaryId?: string;
  stage?: string | undefined;
  startTime?: Date;
  stopTime?: Date;
  userName?: string | undefined;
  noOfItemsProcessed?: number;
  guidId?: string;
}

export interface LogSummaryGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface LogSummaryResponseDTO {
  value?: any | undefined;
}

export interface LogSummaryUpdateRequestDTO {
  logSummaryId?: string;
  stage?: string | undefined;
  startTime?: Date;
  stopTime?: Date;
  userName?: string | undefined;
  noOfItemsProcessed?: number;
  guidId?: string;
}
//..
export interface ModelVersionResponseDTO {
  modelVersionId: number;
  versionDescription?: string | undefined;
  modelName?: string | undefined;
  defaultTestingMode?: string | undefined;
  //timestamp?: Date;
  timestamp?: string;
  userName?: string | undefined;
  capacity?: number;
  testCapacity?: number;
  nominalOutput?: number;
  nominalOutputPercentage?: number;
  nonlinearityPercentage?: number;
  minimumDeadLoad?: number;
  vMin?: number | undefined;
  nMax?: number | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  shellMaterialName?: string | undefined;
  versionHistory?: string | undefined;
  defaultCableLength?: number | undefined;
  resistance?: number;
  ccNumber?: string | undefined;
  accuracyClass?: string | undefined;
  application?: string | undefined;
  processFlowGroupName?: string | undefined;
  modelType?: string | undefined;

  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  noOfGauges: number;
  guidId?: string;
}

export interface NewBatchResponseDTO {
  newBatchNo?: number;
  lastGenerateNumber?: number;
}

export interface NonConformanceLogCreateRequestDTO {
  productId?: number;
  modelVersionId?: number;
  modelName?: string | undefined;
  batchNo?: number;
  stage?: string | undefined;
  timeStamp?: Date;
  defectName?: string | undefined;
  logByUserName?: string | undefined;
  status?: string | undefined;
  solution?: string | undefined;
  whenItWasResolved?: Date;
  resolvedByUserName?: string | undefined;
  comment?: string | undefined;
  guidId?: string;
}

export interface NonConformanceLogGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface NonConformanceLogResponseDTO {
  value?: any | undefined;
}

export interface NonConformanceLogUpdateRequestDTO {
  productId?: number;
  modelVersionId?: number;
  modelName?: string | undefined;
  batchNo?: number;
  stage?: string | undefined;
  timeStamp?: Date;
  defectName?: string | undefined;
  logByUserName?: string | undefined;
  status?: string | undefined;
  solution?: string | undefined;
  whenItWasResolved?: Date;
  resolvedByUserName?: string | undefined;
  comment?: string | undefined;
  guidId?: string;
}

export interface ProblemDetails {
  type?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;

  [key: string]: any;
}

export interface ProductAdditionalInfoCreateRequestDTO {
  productAdditionalInfoId?: number;
  productId?: number;
  inputVoltage?: number;
  cableLenght?: number;
  cableLenghtUnit?: string | undefined;
  guidId?: string;
}

export interface ProductAdditionalInfoGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductAdditionalInfoResponseDTO {
  value?: any | undefined;
}

export interface ProductAdditionalInfoUpdateRequestDTO {
  productAdditionalInfoId?: number;
  productId?: number;
  inputVoltage?: number;
  cableLenght?: number;
  cableLenghtUnit?: string | undefined;
  guidId?: string;
}

export interface ProductCablingEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductCablingEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductCablingEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductCreateRequestDTO {
  productId?: number;
  modelVersionId?: number;
  modelName?: string | undefined;
  modelType?: string | undefined;
  capacity?: number;
  testCapacity?: number;
  timestamp?: Date;
  stage?: string | undefined;
  invoiceId?: string | undefined;
  salesOrderId?: string | undefined;
  cableLength?: number;
  inspectionResult?: number;
  testingMode?: string | undefined;
  processFlowGroupName?: string | undefined;
  thermexPurcharseOrderNo?: string | undefined;
  machiningPurcharseOrderNo?: string | undefined;
  steelPurcharseOrderNo?: string | undefined;
  batchNo?: number;
  loadDirection?: string | undefined;
  calibrationType?: string | undefined;
  weightUnit?: string | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  guidId?: string;
}

export interface ProductFinalUnitCreateRequestDTO {
  productId?: number;
  timeStamp?: Date;
  inputUnit?: string | undefined;
  ouputUnits?: string | undefined;
  indicatorType?: string | undefined;
  indicatorChannel?: number;
  indicatorSerialNo?: string | undefined;
  gradSize?: number;
  pinSize?: number;
  division?: number;
  lowWeight?: number;
  highWeight?: number;
  guidId?: string;
}

export interface ProductFinalUnitGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductFinalUnitResponseDTO {
  value?: any | undefined;
}

export interface ProductFinalUnitUpdateRequestDTO {
  productId?: number;
  timeStamp?: Date;
  inputUnit?: string | undefined;
  ouputUnits?: string | undefined;
  indicatorType?: string | undefined;
  indicatorChannel?: number;
  indicatorSerialNo?: string | undefined;
  gradSize?: number;
  pinSize?: number;
  division?: number;
  lowWeight?: number;
  highWeight?: number;
  guidId?: string;
}

export interface ProductFinalVerifiationEventCreateRequestDTO {
  points?: number;
  verificationResult?: number;
  referenceSerial?: string | undefined;
  testerName?: string | undefined;
  calibratedOutput?: number;
  percentNonlinearity?: number;
  dutZeroPoint?: number;
  refPoint0?: number;
  forcePoint0?: number;
  dutPoint0?: number;
  refPoint1?: number;
  forcePoint1?: number;
  dutPoint1?: number;
  refPoint2?: number;
  forcePoint2?: number;
  dutPoint2?: number;
  refPoint3?: number;
  forcePoint3?: number;
  dutPoint3?: number;
  refPoint4?: number;
  forcePoint4?: number;
  dutPoint4?: number;
  refPoint5?: number;
  forcePoint5?: number;
  dutPoint5?: number;
  refPoint6?: number;
  forcePoint6?: number;
  dutPoint6?: number;
  refPoint7?: number;
  forcePoint7?: number;
  dutPoint7?: number;
  refPoint8?: number;
  forcePoint8?: number;
  dutPoint8?: number;
  refPoint9?: number;
  forcePoint9?: number;
  dutPoint9?: number;
  refPoint10?: number;
  forcePoint10?: number;
  dutPoint10?: number;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductFinalVerifiationEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductFinalVerifiationEventResponseDTO {
  value?: any | undefined;
}

export interface ProductFinalVerifiationEventUpdateRequestDTO {
  points?: number;
  verificationResult?: number;
  referenceSerial?: string | undefined;
  testerName?: string | undefined;
  calibratedOutput?: number;
  percentNonlinearity?: number;
  dutZeroPoint?: number;
  refPoint0?: number;
  forcePoint0?: number;
  dutPoint0?: number;
  refPoint1?: number;
  forcePoint1?: number;
  dutPoint1?: number;
  refPoint2?: number;
  forcePoint2?: number;
  dutPoint2?: number;
  refPoint3?: number;
  forcePoint3?: number;
  dutPoint3?: number;
  refPoint4?: number;
  forcePoint4?: number;
  dutPoint4?: number;
  refPoint5?: number;
  forcePoint5?: number;
  dutPoint5?: number;
  refPoint6?: number;
  forcePoint6?: number;
  dutPoint6?: number;
  refPoint7?: number;
  forcePoint7?: number;
  dutPoint7?: number;
  refPoint8?: number;
  forcePoint8?: number;
  dutPoint8?: number;
  refPoint9?: number;
  forcePoint9?: number;
  dutPoint9?: number;
  refPoint10?: number;
  forcePoint10?: number;
  dutPoint10?: number;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductFinishedEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductFinishedEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductFinishedEventResponseDTO {
  value?: any | undefined;
}

export interface ProductFinishedEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductGaugeEventCreateRequestDTO {
  guageModel?: string | undefined;
  guageLotNo?: string | undefined;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductGaugeEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductGaugeEventUpdateRequestDTO {
  guageModel?: string | undefined;
  guageLotNo?: string | undefined;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductGaugeInspectionEventCreateRequestDTO {
  inspectionResult?: number;
  defectName?: string | undefined;
  gaugeFailed?: number;
  gaugePassed?: number;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductGaugeInspectionEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductGaugeInspectionEventUpdateRequestDTO {
  inspectionResult?: number;
  defectName?: string | undefined;
  gaugeFailed?: number;
  gaugePassed?: number;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductInitialUnitCreateRequestDTO {
  productId?: number;
  timeStamp?: Date;
  inputUnits?: string | undefined;
  outputUnits?: string | undefined;
  guidId?: string;
}

export interface ProductInitialUnitGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductInitialUnitResponseDTO {
  value?: any | undefined;
}

export interface ProductInitialUnitUpdateRequestDTO {
  productId?: number;
  timeStamp?: Date;
  inputUnits?: string | undefined;
  outputUnits?: string | undefined;
  guidId?: string;
}

export interface ProductInitialVerificationEventCreateRequestDTO {
  points?: number;
  verificationResult?: number;
  inspectionResult: boolean;
  referenceSerial?: string | undefined;
  testerName?: string | undefined;
  calibratedOutput?: number;
  percentNonlinearity?: number;
  dutZeroPoint?: number;
  refPoint0?: number;
  forcePoint0?: number;
  dutPoint0?: number;
  refPoint1?: number;
  forcePoint1?: number;
  dutPoint1?: number;
  refPoint2?: number;
  forcePoint2?: number;
  dutPoint2?: number;
  refPoint3?: number;
  forcePoint3?: number;
  dutPoint3?: number;
  refPoint4?: number;
  forcePoint4?: number;
  dutPoint4?: number;
  refPoint5?: number;
  forcePoint5?: number;
  dutPoint5?: number;
  refPoint6?: number;
  forcePoint6?: number;
  dutPoint6?: number;
  refPoint7?: number;
  forcePoint7?: number;
  dutPoint7?: number;
  refPoint8?: number;
  forcePoint8?: number;
  dutPoint8?: number;
  refPoint9?: number;
  forcePoint9?: number;
  dutPoint9?: number;
  refPoint10?: number;
  forcePoint10?: number;
  dutPoint10?: number;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductInitialVerificationEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductInitialVerificationEventUpdateRequestDTO {
  points?: number;
  verificationResult?: number;
  inspectionResult: boolean;
  referenceSerial?: string | undefined;
  testerName?: string | undefined;
  calibratedOutput?: number;
  percentNonlinearity?: number;
  dutZeroPoint?: number;
  refPoint0?: number;
  forcePoint0?: number;
  dutPoint0?: number;
  refPoint1?: number;
  forcePoint1?: number;
  dutPoint1?: number;
  refPoint2?: number;
  forcePoint2?: number;
  dutPoint2?: number;
  refPoint3?: number;
  forcePoint3?: number;
  dutPoint3?: number;
  refPoint4?: number;
  forcePoint4?: number;
  dutPoint4?: number;
  refPoint5?: number;
  forcePoint5?: number;
  dutPoint5?: number;
  refPoint6?: number;
  forcePoint6?: number;
  dutPoint6?: number;
  refPoint7?: number;
  forcePoint7?: number;
  dutPoint7?: number;
  refPoint8?: number;
  forcePoint8?: number;
  dutPoint8?: number;
  refPoint9?: number;
  forcePoint9?: number;
  dutPoint9?: number;
  refPoint10?: number;
  forcePoint10?: number;
  dutPoint10?: number;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

// export interface ProductInventoryEventCreateRequestDTO {
//   productId?: number;
//   userName?: string | undefined;
//   timeStamp?: Date;
//   guidId?: string;
// }

// export interface ProductInventoryEventGetRequestDTO {
//   entityNameId?: any | undefined;
// }

// export interface ProductInventoryEventUpdateRequestDTO {
//   productId?: number;
//   userName?: string | undefined;
//   timeStamp?: Date;
//   guidId?: string;
// }

export interface ProductLabellingEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductLabellingEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductLabellingEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductMovingEventCreateRequestDTO {
  productsToMove: ProductsToMoveDTO[];
  destinationStage: string;
  movingNotes: string;
}

export interface ProductsToMoveDTO {
  testingMode: string;
  sourceStage: string;
  productId: number;
}

export interface ProductMovingEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductMovingEventResponseDTO {
  sourceStage: string | undefined;
  destinationStage: string | undefined;
  movingNotes?: string | undefined;
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}

export interface ProductMovingEventUpdateRequestDTO {
  sourceStage?: string | undefined;
  destinationStage?: string | undefined;
  movingNotes?: string | undefined;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductPictureCreateRequestDTO {
  productId?: number;
  timestamp?: Date;
  userName?: string | undefined;
  stage?: string | undefined;
  fileName?: string | undefined;
  localPathName?: string | undefined;
  basePath?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface ProductPictureGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductPictureResponseDTO {
  value?: any | undefined;
}

export interface ProductPictureUpdateRequestDTO {
  productId?: number;
  timestamp?: Date;
  userName?: string | undefined;
  stage?: string | undefined;
  fileName?: string | undefined;
  localPathName?: string | undefined;
  basePath?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface ProductReceptionEventCreateRequestDTO {
  notes?: string | undefined;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductReceptionEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductReceptionEventResponseDTO {
  value?: any | undefined;
}

export interface ProductReceptionEventUpdateRequestDTO {
  notes?: string | undefined;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductResistorInstallationEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductResistorInstallationEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductResistorInstallationEventResponseDTO {
  value?: any | undefined;
}

export interface ProductResistorInstallationEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductResponseDTO {
  productId: number;
  modelVersionId: number;
  modelName: string;
  modelType: string;
  capacity: number;
  testCapacity: number;
  resistance: number;
  nominalOutput: number;
  nominalOutputPercentage: number;
  nonlinearityPercentage: number;
  timestamp?: Date;
  stage: string;
  currentStatus: string;
  invoiceId?: string | undefined;
  salesOrderId?: string | undefined;
  cableLength?: number;
  inspectionResult: number;
  testingMode: string;
  processFlowGroupName?: string | undefined;
  thermexPurcharseOrderNo?: string | undefined;
  machiningPurcharseOrderNo?: string | undefined;
  steelPurcharseOrderNo?: string | undefined;
  batchNo: number;
  modelVersionGuid?: string;
  hasBeenExercised: boolean;
  loadDirection?: string | undefined;
  calibrationType: string | undefined;
  weightUnit: string | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  isRMA: boolean;
  noOfGauges: number;
  guidId: string;
}

export interface ProductSealingEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductSealingEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductSealingEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductShippingEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductShippingEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductShippingEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductSurfacePreparationEventCreateRequestDTO {
  inspectionResult?: number;
  defectName?: string | undefined;
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductSurfacePreparationEventResponseDTO {
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}

export interface ProductSurfacePreparationEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

// export interface ProductUpdateRequestDTO {
//   productId?: number;
//   modelVersionId?: number;
//   modelName?: string | undefined;
//   modelType?: string | undefined;
//   capacity?: number;
//   testCapacity?: number;
//   timestamp?: Date;
//   stage?: string | undefined;
//   currentStatus?: string | undefined;
//   invoiceId?: string | undefined;
//   salesOrderId?: string | undefined;
//   cableLength?: number;
//   inspectionResult?: number;
//   testingMode?: string | undefined;
//   processFlowGroupName?: string | undefined;
//   thermexPurcharseOrderNo?: string | undefined;
//   machiningPurcharseOrderNo?: string | undefined;
//   steelPurcharseOrderNo?: string | undefined;
//   batchNo?: number;
//   loadDirection?: string | undefined;
//   calibrationType: string | undefined;
//   guidId?: string;
// }

export interface ProductVersionChangedEventCreateRequestDTO {
  productId?: number;
  prevModelVersionId?: number;
  prevModelName?: string | undefined;
  prevModelType?: string | undefined;
  newModelVersionId?: number;
  newModelName?: string | undefined;
  newModelType?: string | undefined;
  comment?: string | undefined;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductVersionChangedEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductVersionChangedEventResponseDTO {
  value?: any | undefined;
}

export interface ProductVersionChangedEventUpdateRequestDTO {
  productId?: number;
  prevModelVersionId?: number;
  prevModelName?: string | undefined;
  prevModelType?: string | undefined;
  newModelVersionId?: number;
  newModelName?: string | undefined;
  newModelType?: string | undefined;
  comment?: string | undefined;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductWiringEventCreateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ProductWiringEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProductWiringEventUpdateRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}

export interface ReferenceCellCalibrationCreateRequestDTO {
  weight?: number;

  refStandardModelName?: string | undefined;
  refStandardSerialNo?: string | undefined;
  lowMeasuredPosition?: number;
  lowCurrent?: number;
  highMeasuredPosition?: number;
  highCurrent?: number;
  guidId?: string;
}

export interface ReferenceCellCalibrationGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ReferenceCellCalibrationResponseDTO {
  value?: any | undefined;
}

export interface ReferenceCellCalibrationUpdateRequestDTO {
  weight?: number;

  refStandardModelName?: string | undefined;
  refStandardSerialNo?: string | undefined;
  lowMeasuredPosition?: number;
  lowCurrent?: number;
  highMeasuredPosition?: number;
  highCurrent?: number;
  guidId?: string;
}

export interface ReferenceCellStandardCreateRequestDTO {
  description: string;
  refStandardModelName?: string;
  refStandardSerialNo?: string;
  capacity: number;
  //outPut?: string | undefined;
  // timestamp?: Date;
  b0?: number;
  b1?: number;
  b2?: number;
  b3?: number;
  b4?: number;
  // guidId?: string;
}

export interface ReferenceCellStandardGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ReferenceCellStandardResponseDTO {
  description: string;
  refStandardModelName?: string | undefined;
  refStandardSerialNo: string;
  capacity?: number;
  timestamp?: Date;
  b0?: number;
  b1?: number;
  b2?: number;
  b3?: number;
  b4?: number;
  guidId: string;
}

export interface ReferenceCellStandardUpdateRequestDTO {
  description: string;
  refStandardModelName?: string | undefined;
  refStandardSerialNo?: string | undefined;
  capacity?: number;
  timestamp?: Date;
  b0?: number;
  b1?: number;
  b2?: number;
  b3?: number;
  b4?: number;
  guidId: string;
}

export interface ShuntResistorCreateRequestDTO {
  value?: number;
  guidId?: string;
}

export interface ShuntResistorGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ShuntResistorResponseDTO {
  value: number;
  Guid: string;
}

export interface ShuntResistorUpdateRequestDTO {
  value?: number;
  guidId?: string;
}

export interface TestCreateRequestDTO {
  timestamp?: Date;
  productId?: number;
  userName?: string | undefined;
  refStandardSerialNo?: string | undefined;

  refStandardModelName?: string | undefined;
  excitationResistance?: number;
  signalResistance?: number;
  guidId?: string;
}

export interface TestGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface TestResponseDTO {
  value?: any | undefined;
}

export interface TestUpdateRequestDTO {
  timestamp?: Date;
  productId?: number;
  userName?: string | undefined;
  refStandardSerialNo?: string | undefined;

  refStandardModelName?: string | undefined;
  excitationResistance?: number;
  signalResistance?: number;
  guidId?: string;
}

export interface TesterCreateRequestDTO {
  testerName?: string | undefined;
  nistTraceAble?: number;
  guidId?: string;
}

export interface TesterGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface TesterResponseDTO {
  testerName: string | undefined;
  nistTraceAble?: number;
  guidId?: string;
}

export interface TesterUpdateRequestDTO {
  testerName?: string | undefined;
  nistTraceAble?: number;
  guidId?: string;
}

export interface TrimmingResistorCreateRequestDTO {
  value?: number;
  guidId?: string;
}

export interface TrimmingResistorGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface TrimmingResistorResponseDTO {
  value: number;
  guidId: string;
}

export interface TrimmingResistorUpdateRequestDTO {
  value?: number;
  guidId?: string;
}

export interface ProductGetRequestByStage {
  stage: string | undefined;
  testingMode?: string | undefined;
  batchno?: number | null;
  filterByBatchNo?: boolean;
}

export interface ProductUpdateStageRequestDTO {
  stage: string | undefined;
  productIds: string[] | undefined;
  inspectionResult: boolean;
  defectName: string;
  gaugeDetails?: GaugeDetails;
  inventoryDetails?: InventoryDetails;
  gaugeInspectionDetails?: GaugeInspectionDetails;
  shippingDetails?: ShippingDetails
}

export interface ShippingDetails {
  invoiceNumber?: string | undefined;

}
export interface ProductSurfacePreparationRePrintLabelRequestDTO {
  stage: string | undefined;
  productIds: string[];
}

export interface ProductPrintActualOutputLabelRequestDTO {
  productIds: string[];
}

export interface TestDataPoint {
  pointName: string;
  pointValues: number;
  pointNumber: number;
}

export interface Points {
  refPoint: number;
  forcePoint: number;
  dutPoint: number;
}

export interface TestEventArgs {
  testData: TestDataPoint[];
  pointsBefore: Points;
  pointsAfter: Points;
}
export interface DefectLogCreateRequestDTO {
  productId: number;
  modelVersionId: number;
  modelName: string;
  modelType: string;
  batchNo: number;
  stage: string;
  timeStamp: Date;
  defect: string;
  status: string;
  solution: string;
  whenItWasResolved: Date;
  resolvedByUserName: string;
  comment: string;
  defectTypeGuid: string;
  guidId: string; // Guid is typically represented as a string in TypeScript
}

export interface DefectLogResponseDTO {
  productId: number;
  modelVersionId: number;
  modelName: string;
  modelType: string;
  batchNo: number;
  stage: string;
  timeStamp: Date;
  defect: string;
  status: string;
  solution: string;
  whenItWasResolved: Date;
  resolvedByUserName: string;
  comment: string;
  defectTypeGuid: string;
  userName: string;
  guidId: string; // Guid is typically represented as a string in TypeScript
}
export interface DefectLogUpdateRequestDTO {
  productId?: number;
  newStage?: string | undefined;
  previousStage?: string | undefined;
  comment?: string | undefined;
  //efectLogGuid?: string;
}
export interface ModelVersionReassinmentRequestDTO {
  version: ModelVersionResponseDTO;
  modelType: string;
  productIds: string[];
}
export interface NCRLogCreateRequestDTO {
  batchNo?: number;
  modelVersionId?: number;
  modelName?: string | undefined;
  modelType?: string | undefined;
  commaDelimitedProductIdsAffected?: string | undefined;
  //nCRLogNo?: number;
  informationAboutTriggerEvent?: string | undefined;
  defectName?: string | undefined;
  comment?: string | undefined;
  timeStamp?: Date;
  minBatchQuantityforTrigger: number;
  totalProductsInBatch?: number;
  defectCount?: number;
  defectTypeTriggerPercentage?: number;
  logUpdateDate?: Date;
  defectTypeGuidId?: string;
  guidId?: string;
}

export interface NCRLogGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface NCRLogUpdateRequestDTO {
  // batchNo?: number;
  // modelVersionId?: number;
  // modelName?: string | undefined;
  // modelType?: string | undefined;
  // commaDelimitedProductIdsAffected?: string | undefined;
  // stage?: string | undefined;
  // informationAboutTriggerEvent?: string | undefined;
  // defectName?: string | undefined;
  comment?: string | undefined;
  // timeStamp?: Date;
  // totalProductsInBatch?: number;
  // defectCount?: number;
  // defectTypeTriggerPercentage?: number;
  // logUpdateDate?: Date;
  // defectTypeGuidId?: string;
  guidId: string;
}

export interface NCRLogResponseDTO {
  batchNo: number;
  modelVersionId: number;
  modelName: string | undefined;
  modelType: string | undefined;
  commaDelimitedProductIdsAffected: string;
   nCRLogNo :number;
  informationAboutTriggerEvent: string | undefined;
  defectName: string | undefined;
  comment: string | undefined;
  timeStamp: Date;
  minBatchQuantityforTrigger: number;
  totalProductsInBatch?: number;
  defectCount?: number;
  defectTypeTriggerPercentage?: number;
  logUpdateDate?: Date;
  defectTypeGuidId?: string;
  guidId: string;
}

export interface TrackingGroupedProductDTO {
  stage: string;
  modelType: string;
  count: number;
  capacity: number;
  modelName: string;
}

export interface ProductGetTrackingDetailRequestDTO {
  stage?: string;
  modelName?: string;
  productId?: number | null;
  GetRequestByProductId?: boolean;
}

export interface BaseEventResponseDTO {
  EventName: string;
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
  AllPropertiesAsJson?: string | undefined;
}
export interface ProductInitialVerificationEventResponseDTO {
  points?: number;
  verificationResult?: number;
  inspectionResult: boolean;
  referenceSerial?: string | undefined;
  testerName?: string | undefined;
  calibratedOutput?: number;
  percentNonlinearity?: number;
  dutZeroPoint?: number;
  refPoint0?: number;
  forcePoint0?: number;
  dutPoint0?: number;
  refPoint1?: number;
  forcePoint1?: number;
  dutPoint1?: number;
  refPoint2?: number;
  forcePoint2?: number;
  dutPoint2?: number;
  refPoint3?: number;
  forcePoint3?: number;
  dutPoint3?: number;
  refPoint4?: number;
  forcePoint4?: number;
  dutPoint4?: number;
  refPoint5?: number;
  forcePoint5?: number;
  dutPoint5?: number;
  refPoint6?: number;
  forcePoint6?: number;
  dutPoint6?: number;
  refPoint7?: number;
  forcePoint7?: number;
  dutPoint7?: number;
  refPoint8?: number;
  forcePoint8?: number;
  dutPoint8?: number;
  refPoint9?: number;
  forcePoint9?: number;
  dutPoint9?: number;
  refPoint10?: number;
  forcePoint10?: number;
  dutPoint10?: number;
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
  verificationType: string; // This should be Auto or Manual
}

export interface ProductFinalVerificationEventResponseDTO {
  points?: number;
  verificationResult?: number;
  inspectionResult: boolean;
  referenceSerial?: string | undefined;
  testerName?: string | undefined;
  calibratedOutput?: number;
  percentNonlinearity?: number;
  dutZeroPoint?: number;
  refPoint0?: number;
  forcePoint0?: number;
  dutPoint0?: number;
  refPoint1?: number;
  forcePoint1?: number;
  dutPoint1?: number;
  refPoint2?: number;
  forcePoint2?: number;
  dutPoint2?: number;
  refPoint3?: number;
  forcePoint3?: number;
  dutPoint3?: number;
  refPoint4?: number;
  forcePoint4?: number;
  dutPoint4?: number;
  refPoint5?: number;
  forcePoint5?: number;
  dutPoint5?: number;
  refPoint6?: number;
  forcePoint6?: number;
  dutPoint6?: number;
  refPoint7?: number;
  forcePoint7?: number;
  dutPoint7?: number;
  refPoint8?: number;
  forcePoint8?: number;
  dutPoint8?: number;
  refPoint9?: number;
  forcePoint9?: number;
  dutPoint9?: number;
  refPoint10?: number;
  forcePoint10?: number;
  dutPoint10?: number;
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
  verificationType: string; // This should be Auto or Manual

  // public decimal? usedTrimResistor1 { get; init; }
  // public decimal? usedTrimResistor2 { get; init; }
  // public decimal? usedShuntResistor1 { get; init; }
  // public decimal? usedShuntResistor2 { get; init; }
  // public string VerificationType { get; init; }
}

export interface ProductGaugeEventResponseDTO {
  productId: number;
  guageModel: string;
  guageLotNo: string;
  userName: string;
  timeStamp: Date;
  guidId: string;
}

export interface ProductAddResistorEventResponseDTO {
  productId: number;
  inspectionResult: boolean;
  defectName: string;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}
export interface ProductSurfacePreparationEventGetRequestDTO {
  productId?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  guidId?: string;
}
export interface ProductWiringEventResponseDTO {
  productId: number;
  inspectionResult: boolean;
  defectName: string;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}
export interface ProductGaugeInspectionEventResponseDTO {
  inspectionResult: boolean;
  defectName?: string | undefined;
  gaugeFailed?: number;
  gaugePassed?: number;
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
  //Int32 InspectionResult, string DefectName, Int32 GaugeFailed, Int32 GaugePassed, Int32 ProductId, string UserName, DateTime TimeStamp, Guid GuidId
}
export interface ProductCablingEventResponseDTO {
  productId: number;
  inspectionResult: boolean;
  defectName: string;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}

export interface ProductSealingEventResponseDTO {
  productId: number;
  inspectionResult: boolean;
  defectName: string;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}

export interface ProductLabellingEventResponseDTO {
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}
export interface ProductShippingEventResponseDTO {
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
}

export interface ProductInventoryEventResponseDTO {
  productId: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
  salesOrderNo?: string | undefined;
}

export interface TrackingReportDetailResponceDTO {
  products: ProductResponseDTO;
  surfacePreparationEvents?: ProductSurfacePreparationEventResponseDTO[];
  gaugeEvents?: ProductGaugeEventResponseDTO[];
  gaugeInspectionEvents?: ProductGaugeInspectionEventResponseDTO[];
  wiringEvents?: ProductWiringEventResponseDTO[];
  cablingEvents?: ProductCablingEventResponseDTO[];
  initialTestEvents?: ProductInitialVerificationEventResponseDTO[];
  addResistorEvents?: ProductAddResistorEventResponseDTO[];
  sealingEvents?: ProductSealingEventResponseDTO[];
  finalTestEvents?: ProductFinalVerificationEventResponseDTO[];
  labellingEvents?: ProductLabellingEventResponseDTO[];
  inventoryEvents?: ProductInventoryEventResponseDTO[];
  shippingEvents?: ProductShippingEventResponseDTO[];
  movingEvents?: ProductMovingEventResponseDTO[];
  defectLogs?: DefectLogResponseDTO[];
  productCertificates?: ProductFullCertificateResponseDTO[];
  //    public record DefectLogResponseDTO(Int32 ProductId, Int32 ModelVersionId, string ModelName, string ModelType, Int32 BatchNo, string Stage, DateTime TimeStamp, string Defect, string Status, string Solution, DateTime WhenItWasResolved, string ResolvedByUserName, string Comment, Guid DefectTypeGuid, string UserName, Guid GuidId);

  //ncrLogs?: NCRLogResponseDTO[];
}

export interface CalibrationData {
  id: string;
  weightTester: number;
  readOut: number;
}
export interface CalibrationDataPlusScaleError extends CalibrationData {
  id: string;
  weightTester: number;
  readOut: number;
  expectedReadOut: number;
  fullScaleError: number;
}

export interface ProductCertificateGetRequestDTO {
  productId: number | null;
  certificateType?: string | null;
  partOfCertificateInfo?: string | null;
}

export interface ProductCertificateResponseDTO {
  //productCertificateId: number;
  productId: number;
  certificateType: string;
  certificateNo: string;
  timestamp: Date;
  userName: string | undefined;
  guidId: string;
}

export interface ProductFullCertificateResponseDTO {
  //productCertificateId: number;
  productId: number;
  certificateType: string;
  certificateNo: string;
  jsonCertificateTypeDetails: string;
  timestamp: Date;
  userName: string | undefined;
  guidId: string;
}

export interface PartialProductCertificatePrintByGuidRequestDTO {
  CertificateGuid: string;
  reportType: string;
}

export interface PartialProductCertificatePrintByProductIdRequestDTO {
  ProductIds: number[];
  reportType: string;
}

export interface CertificateBase {
  productId: number;
  modelName: string;
  calibrationTechnician: string;
  checkedBy: string;
  checkedByDesignation: string;

  certificateNo: string;
  testResult: string;
  capacity: number;
  calibrationDate: string;
  calibrationDueDate?: string | null;
}
export interface WesternScaleFormData extends CertificateBase {
  customerName: string;
  rma: string;
  productId: number;
  modelName: string;
  salesOrder: string;
  certificateNo: string;
  calibrationDate: string;
  calibrationDueDate: string;
  testResult: string;
  indicatorModel: string;
  indicatorSerialNo: string;
  // These four are not in WesterScale certificate
  // indicatorModuleId: string;
  // transmitterModel: string;
  // transmitterSerialNo: string;
  // transmitterModuleId: string;

  testPinDiameterStart: string;
  testPinDiameterEnd: string; // cant see this on the certificate
  loadCellId: string; // found  this on the certificate
  outputUnit: string;
  refWeightUnit: string;
  graduationSize: string;
  testMode: string;

  notes: string;
  calibrationTechnician: string;
  checkedBy: string;
  checkedByDesignation: string;

  beforeCalibrationData: CalibrationData[];
  afterCalibrationData: CalibrationData[];
}

export interface MantraCourtFormData extends CertificateBase {
  //sales segment
  customerName: string;
  rma: string;
  salesOrder: string;

  productId: number;
  modelName: string;

  certificateNo: string;
  calibrationDate: string;
  calibrationDueDate: string;
  testResult: string;

  //CalibrationInfoParts segment
  indicatorModel: string;
  indicatorSerialNo: string;
  indicatorModuleId: string;
  transmitterModel: string;
  transmitterSerialNo: string;
  transmitterModuleId: string;
  testPinDiameterStart: string;
  testPinDiameterEnd: string;
  graduationSize: string;
  outputUnit: string;
  refWeightUnit: string;
  testMode: string;

  notes: string;
  calibrationTechnician: string;
  checkedBy: string;
  checkedByDesignation: string;

  beforeCalibrationData: CalibrationData[];
  afterCalibrationData: CalibrationData[];
}

export interface StandardCertificateType extends CertificateBase {
  /** Generated by system (day-month-year-serialNo-) */
  certificateNo: string;

  /** Generated by system */
  calibrationDate: string;

  /** Pass/Fail from final verification event */
  testResult: string;

  /** From product */
  productId: number;

  /** From product */
  modelName: string;

  /** From product */
  capacity: number;

  /** Decimal CalibratedOutput with output unit */
  outputAtCapacity: number;

  /** From product */
  cableLength: number;

  /** From final event */
  referenceSerial: string;

  /** From product */
  safeLoad: number;

  /** From product */
  ultimateLoad: number;

  /** From product */
  compensatedTempRangeLow: number;

  /** From product */
  compensatedTempRangeHigh: number;

  /** From product */
  //ratedExcitation: number; // this will soon become RatedExcitationMinRatedExcitationMax
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  //ratedExcitationMin: number;
  //ratedExcitationMax: number;
  //        public int RatedExcitationMin { get; init; }
  //public int RatedExcitationMax { get; init; }
  operatingTempMin: number;
  operatingTempMax: number;
  /** From product - both input and output resistance */
  inputResistance: number;

  /** From product */
  outputResistance: number;
  calibrationTechnician: string;
  checkedBy: string;
  checkedByDesignation: string;

  afterCalibrationData: CalibrationData[];
}

export interface ZeroTenFormData extends CertificateBase {
  customerName: string;
  rma: string;
  productId: number;
  modelName: string;
  salesOrder: string;
  certificateNo: string;
  calibrationDate: string;
  calibrationDueDate: string;
  testResult: string;

  indicatorModel: string;
  indicatorSerialNo: string;
  indicatorModuleId: string;

  transmitterModel: string;
  transmitterSerialNo: string;
  transmitterModuleId: string;

  testPinDiameterStart: string;
  testPinDiameterEnd: string;
  outputUnit: string;
  refWeightUnit: string;
  graduationSize: string;
  testMode: string;
  targetWeight0: number;
  targetWeight10: number;
  wiringRed: string;
  wiringBlack: string;
  wiringWhite: string;
  wiringGreen: string;
  wiringShield: string;
  inputVoltage: number;
  cableLenght: number;
  notes: string;
  calibrationTechnician: string;
  checkedBy: string;
  checkedByDesignation: string;

  afterCalibrationData: CalibrationDataPlusScaleError[];
}

export interface FourtyTwentyFormData extends CertificateBase {
  customerName: string;
  rma: string;
  productId: number;
  modelName: string;
  salesOrder: string;
  certificateNo: string;
  calibrationDate: string;
  calibrationDueDate: string;
  testResult: string;

  indicatorModel: string;
  indicatorSerialNo: string;
  indicatorModuleId: string;

  transmitterModel: string;
  transmitterSerialNo: string;
  transmitterModuleId: string;

  testPinDiameterStart: string;
  testPinDiameterEnd: string;
  outputUnit: string;
  refWeightUnit: string;

  graduationSize: string;
  testMode: string;
  targetWeight4: number;
  targetWeight20: number;
  wiringRed: string;
  wiringBlack: string;
  wiringWhite: string;
  wiringGreen: string;
  wiringShield: string;
  inputVoltage: number;
  cableLenght: number;
  notes: string;
  calibrationTechnician: string;
  checkedBy: string;
  checkedByDesignation: string;

  afterCalibrationData: CalibrationDataPlusScaleError[];
}

export interface IndicatorsModel {
  indicatorType: string;
  name: string;
  guidId: string;
}

export interface TransmitterModelModel {
  transmitterType: string;
  name: string;
  guidId: string;
}

export interface ReportRequestDTO {
  AllStagesAndEvents: StageAndFields[];
  startDate: string | null;
  endDate: string | null;
  ProductIdStart: number | null;
  ProductIdEnd: number | null;
  startBatchNo: number | null;
  endBatchNo: number | null;
  modelType: string | null;
  modelVersionId: number | null;
  modelName: string | null;
  stage: string | null;
  gauge: string | null;
  lotNo: string | null;
  testingMode: string | null;
  calibration: string | null;
  hasDefectType: string | null;
  defectType: string | null;
  employee: string | null;
}

export interface SignatureManagerResponseDTO {
  signatureManagerId: number;
  description: string;
  officialName: string;
  designation: string;
  filename: string;
  guidId: string;
}

export interface EMailSenderResponseDTO {
  resourceName: string;
  description: string;
  email: string;
  officialName: string;
  designation: string;
  guidId: string;
}
