//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

// export interface AuthCodeDto {
//   code?: string | undefined;
//   userId?: string | undefined;
// }

export interface PartUsedCreateRequestDTO {
  rMANumber?: number;
  productId?: string | undefined;
  partCode?: string | undefined;
  dateUsed?: Date;
  userName?: string | undefined;
  partDescription?: string | undefined;
  quantity?: number;
  cost?: string | undefined;
  notes?: string | undefined;
  guidId?: string;
}

export interface PartUsedGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface PartUsedResponseDTO {
  value?: any | undefined;
}

export interface PartUsedUpdateRequestDTO {
  rMANumber?: number;
  productId?: string | undefined;
  partCode?: string | undefined;
  dateUsed?: Date;
  userName?: string | undefined;
  partDescription?: string | undefined;
  quantity?: number;
  cost?: string | undefined;
  notes?: string | undefined;
  guidId?: string;
}

export interface ProblemDetails {
  type?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;

  [key: string]: any;
}
export interface RMANextNumberCreateRequestDTO {
  nextNumber?: number;
  guidId?: string;
}

export interface RMANextNumberResponseDTO {
  nextNumber: number;
  guidId?: string;
}

export interface RMANextNumberUpdateRequestDTO {
  nextNumber?: number;
  guidId?: string;
}

export interface RMAProblemTypeCreateRequestDTO {
  problemType?: string | undefined;
  guidId?: string;
}
export interface RMACreateRequestDTO {
  // rMANumber: number;
  customerEmail?: string | undefined;
  dateIssued?: Date;
  dateReceived?: Date;
  rMAProblemDescription?: string | undefined;
  stage?: string | undefined;
  salesPerson?: string | undefined;
  companyName?: string | undefined;
  contactName?: string | undefined;
  street?: string | undefined;
  city?: string | undefined;
  province?: string | undefined;
  zipCode?: string | undefined;
  country?: string | undefined;
  phoneNumber?: string | undefined;

  notes?: string | undefined;
  pinDiameter?: number;
  guidId?: string;
  createContact: boolean;
}

export interface RMAEventCreateRequestDTO {
  rMANumber?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  status?: string | undefined;
  notes?: string | undefined;
  guidId?: string;
}

export interface RMAEventGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAEventResponseDTO {
  value?: any | undefined;
}

export interface RMAEventUpdateRequestDTO {
  rMANumber?: number;
  userName?: string | undefined;
  timeStamp?: Date;
  status?: string | undefined;
  notes?: string | undefined;
  guidId?: string;
}

export interface RMAGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAProblemTypeCreateRequestDTO {
  problemType?: string | undefined;
  guidId?: string;
}

export interface RMAProblemTypeGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAProblemTypeResponseDTO {
  value?: any | undefined;
}

export interface RMAProblemTypeUpdateRequestDTO {
  problemType?: string | undefined;
  guidId?: string;
}

export interface RMAProductCertificateCreateRequestDTO {
  productCertificateId?: number;
  rMANumber?: number;
  productId?: string | undefined;
  certifcateType?: string | undefined;
  jsonData?: string | undefined;
  timestamp?: Date;
  capacity?: number;
  guidId?: string;
}

export interface RMAProductCertificateGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAProductCertificateResponseDTO {
  value?: any | undefined;
}

export interface RMAProductCertificateUpdateRequestDTO {
  productCertificateId?: number;
  rMANumber?: number;
  productId?: string | undefined;
  certifcateType?: string | undefined;
  jsonData?: string | undefined;
  timestamp?: Date;
  capacity?: number;
  guidId?: string;
}

export interface RMAProductCreateRequestDTO {
  rMANumber?: number;
  productId?: string | undefined;
  productType?: string | undefined;
  problemType?: string | undefined;
  solution?: string | undefined;
  problemDetails?: string | undefined;
  solutionDetails?: string | undefined;
  repairMade?: string | undefined;
  userName?: string | undefined;
  date?: Date;
  timeTakenInMinutes?: number;
  guidId?: string;
}

export interface RMAProductGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAProductResponseDTO {
  value?: any | undefined;
}

export interface RMAProductTypeCreateRequestDTO {
  productType?: string | undefined;
  description?: string | undefined;
  warrantyPeriodInMonths?: number;
  weight?: number;
  length?: number;
  width?: number;
  height?: number;
  volume?: number;
  density?: number;
  guidId?: string;
}

export interface RMAProductTypeGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAProductTypeResponseDTO {
  value?: any | undefined;
}

export interface RMAProductTypeUpdateRequestDTO {
  productType?: string | undefined;
  description?: string | undefined;
  warrantyPeriodInMonths?: number;
  weight?: number;
  length?: number;
  width?: number;
  height?: number;
  volume?: number;
  density?: number;
  guidId?: string;
}

export interface RMAProductUpdateRequestDTO {
  rMANumber?: number;
  productId?: string | undefined;
  productType?: string | undefined;
  problemType?: string | undefined;
  solution?: string | undefined;
  problemDetails?: string | undefined;
  solutionDetails?: string | undefined;
  repairMade?: string | undefined;
  userName?: string | undefined;
  date?: Date;
  timeTakenInMinutes?: number;
  guidId?: string;
}

// Supporting interfaces for the referenced DTOs
export interface RMAResponseDTO {
  rmaNumber: number;
  customerEmail: string;
  dateIssued?: Date;
  dateReceived?: Date;
  rmaProblemDescription: string;
  stage: string;
  salesPerson: string;
  companyName: string;
  contactName: string;
  street?: string;
  city?: string;
  province?: string;
  zipCode?: string;
  country?: string;
  phoneNumber?: string;
  notes: string;
  pinDiameter?: number;
  draftAssessment: boolean;
  salesOrderId?: string;
  guidId: string; // UUID string
}

export interface RMASolutionTypeCreateRequestDTO {
  solution?: string | undefined;
  guidId?: string;
}

export interface RMASolutionTypeGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMASolutionTypeResponseDTO {
  value?: any | undefined;
}

export interface RMASolutionTypeUpdateRequestDTO {
  solution?: string | undefined;
  guidId?: string;
}

export interface RMAStatusCreateRequestDTO {
  status?: string | undefined;
  minNoOfDaysToReSendNotification?: number;
  guidId?: string;
}

export interface RMAStatusGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMAStatusResponseDTO {
  value?: any | undefined;
}

export interface RMAStatusUpdateRequestDTO {
  status?: string | undefined;
  minNoOfDaysToReSendNotification?: number;
  guidId?: string;
}

export interface RMATokenCreateRequestDTO {
  userId?: string | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  expiry?: number;
  createdAt?: Date;
  guidId?: string;
}

export interface RMATokenGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RMATokenResponseDTO {
  userId?: string | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  expiry?: number;
  createdAt?: Date;
  guidId?: string;
}

export interface RMATokenUpdateRequestDTO {
  userId?: string | undefined;
  accessToken?: string | undefined;
  refreshToken?: string | undefined;
  expiry?: number;
  createdAt?: Date;
  guidId?: string;
}

export interface RMAUpdateRequestDTO {
  rMANumber?: number;
  customerEmail?: string | undefined;
  dateIssued?: Date;
  dateReceived?: Date;
  rMAProblemDescription?: string | undefined;
  status?: string | undefined;
  salesPerson?: string | undefined;
  companyName?: string | undefined;
  contactName?: string | undefined;
  city?: string | undefined;
  province?: string | undefined;
  zipCode?: string | undefined;
  country?: string | undefined;
  phoneNumber?: string | undefined;

  notes?: string | undefined;
  pinDiameter?: number;
  guidId?: string;
}

export interface RepairTypeCreateRequestDTO {
  rMAType?: string | undefined;
  guidId?: string;
}

export interface RepairTypeGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface RepairTypeResponseDTO {
  value?: any | undefined;
}

export interface RepairTypeUpdateRequestDTO {
  rMAType?: string | undefined;
  guidId?: string;
}

export interface PackageReceivedEventCreateRequestDTO {
  rMANumber: number;
  notes: string | undefined;
  timeStamp?: Date;
}

export interface CloseRMAEventCreateRequestDTO {
  rMANumber: number;
  notes: string | undefined;
 
}


export interface SalesOrderAddedEventCreateRequestDTO {
  rMANumber: number;
  salesOrderId: string;
  notes: string | undefined;
}

export interface RepairInProgressEventCreateRequestDTO {
  rMANumber: number;
  notes: string | undefined;
}

export interface TrackingGroupedProductDTO {
  //ModelName: string ;
  stage: string;
  count: number;
}

export class TrackReport {
  // ModelName: string = "RMA";
  Total: number = 0;
  LabelSentValue: number = 0;
  PackageReceivedValue: number = 0;
  ProductAssessedValue: number = 0;
  SalesOrderAddedValue: number = 0;
  RepairInProgressValue: number = 0;
  RMACLOSEDValue: number = 0;
}

export interface RMAGetTrackingDetailRequestDTO {
  stage?: string;
  //modelName?: string;
  rMANumber?: number | null;
  GetRequestByrMANumber?: boolean;
}

interface LabelSentEventResponseDTO {
  rmaNumber: number;
  userName: string;
  timeStamp: Date; // ISO date string
  senderEmail: string;
  receiverEmail: string;
  message: string;
  guidId: string; // UUID string
}

export interface PackageReceivedEventResponseDTO {
  rmaNumber: number;
  userName: string;
  timeStamp: Date; // ISO date string
  notes: string;
  guidId: string; // UUID string
}

export interface ProductAssessedEventResponseDTO {
  rmaNumber: number;
  userName: string;
  timeStamp: Date; // ISO date string
  notes: string;
  guidId: string; // UUID string
}

export interface SalesOrderAddedEventResponseDTO {
  rmaNumber: number;

  userName: string;
  timeStamp: Date; // ISO date string
  notes: string;
  guidId: string; // UUID string
}

export interface RepairInProgressEventResponseDTO {
  rmaNumber: number;
  userName: string;
  timeStamp: Date; // ISO date string
  notes: string;
  guidId: string; // UUID string
}

export interface RMACloseEventResponseDTO {
  rmaNumber: number;
  userName: string;
  timeStamp: Date; // ISO date string
  notes: string;
  guidId: string; // UUID string
}

// Main interface equivalent to RMATrackingReportDetailResponceDTO
export interface RMATrackingReportDetailResponseDTO {
  products: RMAResponseDTO;
  labelSentEvents: LabelSentEventResponseDTO[];
  packageReceivedEvents?: PackageReceivedEventResponseDTO[] | null;
  productAssessedEvents?: ProductAssessedEventResponseDTO[] | null;
  salesOrderAddedEvents?: SalesOrderAddedEventResponseDTO[] | null;
  repairInProgressEvents?: RepairInProgressEventResponseDTO[] | null;
  rmaClosedEvents?: RMACloseEventResponseDTO[] | null;
}

export interface BaseEventResponseDTO {
  EventName: string;
  RMANumber: number;
  userName: string | undefined;
  timeStamp: Date;
  guidId: string;
  AllPropertiesAsJson?: string | undefined;
}

// Assessment DTOs

export interface ProductAssessedEventCreateRequestDTO {
  rmaNumber: number;
  products: ProductItemDTO[];
  notes: string | undefined;
  assessmentStatus: boolean;
}

export interface RepairItemDTO {
  repairItemId: number;
  description: string;
  date: Date;
  hoursUsed: number;
}

export interface PartItemDTO {
  partItemId: number;
  description: string;
  quantity: number;
}

export interface ProductItemDTO {
  productCapacity: number;
  productUnit: string;
  serialNo: string;
  modelNo: string;
  calibrationType: "Tension" | "Compression";
  warrantyCheck: boolean;
  solutionType: string;
  solutionNotes: string;
  problemType: string;
  problemNotes: string;
  repairsDone: RepairItemDTO[];
  partsUsed: PartItemDTO[];
}

// export interface RMAAssessmentResponseDTO {
//   rmaNumber: number;
//   products: ProductItemDTO[];
//   userName: string;
//   timeStamp: Date;
//   guidId: string;
// }

export interface SolutionTypeResponseDTO {
  solutionType: string;
  description?: string;
  guidId: string;
}

export interface LabelSentEventCreateRequestDTO {
  senderEmail: string;
  senderName: string;
  receiverEmail: string;
  subject: string;
  message: string;
  rmaNumber: number;
  contactName: string;
}

export interface RMAGetRequestByStage {
  Stage: string | undefined;
  DraftAssessment: boolean;
}

export interface ProductMovingEventCreateRequestDTO {
  productsToMove: ProductsToMoveDTO[];
  destinationStage: string;
  movingNotes: string;
}
