//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface ModelCreateRequestDTO {
  modelName?: string | undefined;
  modelTypeName?: string | undefined;
  modelDescription?: string | undefined;
  guidId?: string;
}

export interface ModelGetRequestDTO {
  modelName?: string | undefined;
}

export interface ModelResponseDTO {
  guidId?: string;
  modelName?: string | undefined;
  modelTypeName?: string | undefined;
  modelDescription?: string | undefined;
  modelVersions?: ModelVersionResponseDTO[] | undefined;
}

export interface ModelTypeCreateRequestDTO {
  modelTypeName?: string | undefined;
  processFlowGroupName?: string | undefined;
  guidId?: string;
}

export interface ModelTypeGetRequestDTO {
  jsonValue?: string | undefined;
}

export interface ModelTypeResponseDTO {
  guidId?: string | undefined;
  modelTypeName?: string | undefined;
  processFlowGroupName?: string | undefined;
  models?: ModelResponseDTO[] | undefined;
}

export interface ModelTypeUpdateRequestDTO {
  modelTypeName?: string | undefined;
  processFlowGroupName?: string | undefined;
  guidId?: string;
}

export interface ModelUpdateRequestDTO {
  modelName?: string | undefined;
  modelTypeName?: string | undefined;
  modelDescription?: string | undefined;
  guidId?: string;
}

export interface ModelVersionCreateRequestDTO {
  modelVersionId: number;
  versionDescription?: string | undefined;
  modelVersionName?: string | undefined;
  modelName?: string | undefined;
  defaultTestingMode?: string | undefined;
  userName?: string | undefined;
  capacity?: number;
  testCapacity?: number;
  nominalOutput?: number;
  nominalOutputPercentage?: number;
  nonlinearityPercentage?: number;
  minimumDeadLoad?: number;
  versionHistory?: string;
  vMin?: number | null | undefined;
  nMax?: number | null | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  shellMaterialName?: string | undefined;
  defaultCableLength?: number | null | undefined;
  resistance?: number;
  ccNumber?: string | undefined;
  accuracyClass?: string | undefined;
  application?: string | undefined;
  guidId?: string;
}

export interface ModelVersionDocumentCreateRequestDTO {
  modelVersionId?: number;
  modelName?: string | undefined;
  modelVersionDocumentId?: number;
  documentDescription?: string | undefined;
  stages: string[];
  documentDrive?: string | undefined;
  documentPath?: string | undefined;
  documentGuid: string;
  documentname?: string | undefined;
  userName: string | undefined;
  guidId?: string;
}

export interface ModelVersionDocumentResponseDTO {
  modelVersionId: number;
  modelName: string;
  modelVersionDocumentId: number;
  documentDescription: string;
  stage: string;
  documentDrive: string;
  documentPath: string;
  documentGuid: string;
  documentname: string;
  timestamp: Date;
  userName: string;
  guidId: string;
}

export interface ModelVersionDocumentUpdateRequestDTO {
  modelVersionId?: number;
  modelName?: string | undefined;
  modelVersionDocumentId?: number;
  documentDescription?: string | undefined;
  stage?: string | undefined;
  documentDrive?: string | undefined;
  documentPath?: string | undefined;
  documentGuid: string;
  documentname?: string | undefined;
  timestamp?: Date;
  userName?: string | undefined;
  guidId?: string;
}

export interface ModelVersionResponseDTO {
  modelVersionId: number;
  versionDescription?: string | undefined;
  modelName: string | undefined;
  defaultTestingMode?: string | undefined;
  //timestamp: Date;
  timestamp: string;
  userName?: string | undefined;
  capacity?: number;
  testCapacity?: number;
  nominalOutput?: number;
  nominalOutputPercentage?: number;
  nonlinearityPercentage?: number;
  minimumDeadLoad?: number;
  vMin?: number;
  nMax?: number;
  safeLoad?: number;
  ultimateLoad?: number;
  shellMaterialName?: string | undefined;
  versionHistory?: string | undefined;
  defaultCableLength?: number;
  resistance?: number;
  ccNumber?: string | undefined;
  accuracyClass?: string | undefined;
  application?: string | undefined;
  guidId?: string;

  compensatedTempRangeLow: number;
  compensatedTempRangeHigh: number;
  ratedExcitationMin: number;
  ratedExcitationMax: number;
  operatingTempMin: number;
  operatingTempMax: number;
  noOfGauges: number ;
  testpoints: DefaultTestPointResponseDTO[]; //| undefined;
}

export interface ModelVersionResponseDTOWtDefaultTestPoints {
  modelVersionId: number;
  versionDescription?: string | undefined;
  modelName: string | undefined;
  defaultTestingMode?: string | undefined;
  //timestamp: Date;
  timestamp: string;
  userName?: string | undefined;
  capacity?: number;
  testCapacity?: number;
  nominalOutput?: number;
  nominalOutputPercentage?: number;
  nonlinearityPercentage?: number;
  minimumDeadLoad?: number;
  vMin?: number;
  nMax?: number;
  safeLoad?: number;
  ultimateLoad?: number;
  shellMaterialName?: string | undefined;
  versionHistory?: string | undefined;
  defaultCableLength?: number;
  resistance?: number;
  ccNumber?: string | undefined;
  accuracyClass?: string | undefined;
  application?: string | undefined;
  guidId?: string;
  testpoints: string | undefined;
}

export interface ModelVersionUpdateRequestDTO {
  modelVersionId?: number;
  versionDescription?: string | undefined;
  modelName?: string | undefined;
  defaultTestingMode?: string | undefined;
  userName?: string | undefined;
  capacity?: number;
  testCapacity?: number;
  nominalOutput?: number;
  nominalOutputPercentage?: number;
  nonlinearityPercentage?: number;
  minimumDeadLoad?: number;
  vMin?: number | null | undefined;
  nMax?: number | null | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  shellMaterialName?: string | undefined;
  versionHistory?: string | undefined;
  defaultCableLength?: number | null | undefined;
  resistance?: number;
  ccNumber?: string | undefined;
  accuracyClass?: string | undefined;
  application?: string | undefined;
  guidId?: string;
}

export interface ProblemDetails {
  type?: string | undefined;
  title?: string | undefined;
  status?: number | undefined;
  detail?: string | undefined;
  instance?: string | undefined;

  [key: string]: any;
}

export interface ProcessFlowGroupCreateRequestDTO {
  processFlowGroupName?: string | undefined;
  defaultTestingMode?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface ProcessFlowGroupGetRequestDTO {
  entityNameId?: any | undefined;
}

export interface ProcessFlowGroupResponseDTO {
  guidId?: string;
  processFlowGroupName?: string | undefined;
  defaultTestingMode?: string | undefined;
  description?: string | undefined;
  //  modelTypeResponseDTO?: ModelTypeResponseDTO[] | undefined;
}

export interface ProcessFlowGroupUpdateRequestDTO {
  processFlowGroupName?: string | undefined;
  defaultTestingMode?: string | undefined;
  description?: string | undefined;
  guidId?: string;
}

export interface DefaultTestPointCreateRequestDTO {
  modelVersionId: number;
  modelName?: string | undefined;
  order?: number;
  versionGuid?: string;
  capacityDefaultTestPoint: number;
  guidId?: string;
}

export interface DefaultTestPointResponseDTO {
  modelVersionId: number;
  modelName: string | undefined;
  order: number;
  versionGuid: string;
  capacityDefaultTestPoint?: number;
  guidId: string;
}

export interface DefaultTestPointUpdateRequestDTO {
  modelVersionId?: number;
  modelName?: string | undefined;
  order?: number;
  versionGuid?: string;
  capacityDefaultTestPoint?: number;
  guidId?: string;
}
///
//public record ModelVersionDocumentGetRequestDTO(int ModelVersionId, string ModelName);

export interface ModelVersionDocumentGetRequestDTO {
  modelVersionId: number;
  modelName?: string;
  AggregateStages: boolean;
}

export interface ModelVersionDocumenttDeleteRequestDTO {
  guidId: string;
}

export interface ModelVersionGetRequestDTO {
  modelName: string;
}
export interface ModelTypeGetRequestDTO {
  jsonValue?: string | undefined;
}

export interface MaxVersionResponseDTO {
  modelVersionId: number;
  versionDescription?: string | undefined;
  modelName: string;
  modelType?: string | undefined;
  defaultTestingMode?: string | undefined;
  capacity: number;
  testCapacity: number;
  nominalOutput?: number;
  nominalOutputPercentage?: number;
  nonlinearityPercentage?: number;
  minimumDeadLoad?: number;
  vMin?: number | null | undefined;
  nMax?: number | null | undefined;
  safeLoad?: number;
  ultimateLoad?: number;
  shellMaterialName?: string | undefined;
  versionHistory?: string | undefined;
  defaultCableLength?: number | null;
  resistance?: number;
  ccNumber?: string | undefined;
  accuracyClass?: string | undefined;
  application?: string | undefined;
  guidId: string;
  maxVersion: number;
  processFlowGroup?: string | undefined;
  defaultTestPoints: DefaultTestPointResponseDTO[];
}

export interface ModelVersionGetMaxVersionDTO {
  modelName: string;
  modelType: string;
}
export interface ModelVersionGetEditableVersionDTO {
  modelName: string;
  modelType: string;
  guidId: string;
}

export interface ModelVersionDeleteRequestDTO {
  guidId: string;
}

export interface ModelVersionUpdateAndDefaultTestPointCreateRequestDTO {
  modelversions: ModelVersionUpdateRequestDTO;
  testpoints: DefaultTestPointCreateRequestDTO[]; //| undefined;
}

export interface ModelVersionCreateAndDefaultTestPointCreateRequestDTO {
  modelversions: ModelVersionCreateRequestDTO;
  testpoints: DefaultTestPointCreateRequestDTO[]; //| undefined;
}
