//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AddPOEventCreateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface AddPOEventResponseDTO {
    value?: any | undefined;
}

export interface AddPOEventUpdateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface ApprovalEventCreateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface ApprovalEventResponseDTO {
    value?: any | undefined;
}

export interface ApprovalEventUpdateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface CloseRequestEventCreateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface CloseRequestEventResponseDTO {
    value?: any | undefined;
}

export interface CloseRequestEventUpdateRequestDTO {
    materialRequestId?: string;
    userName?: string | undefined;
    timeStamp?: Date;
    notes?: string | undefined;
    guidId?: string;
}

export interface KanbanContainerCreateRequestDTO {
    partCode?: string | undefined;
    barcodeCode?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId?: string;
}

export interface KanbanContainerResponseDTO {
    partCode: string ;
    barcodeCode: string ;
    description: string ;
    supplier: string;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId: string;
}

export interface KanbanContainerUpdateRequestDTO {
    partCode?: string | undefined;
    barcodeCode?: string | undefined;
    description?: string | undefined;
    supplier?: string | undefined;
    triggerQuantity?: number | undefined;
    leadTimeInDays?: number | undefined;
    guidId?: string;
}

export interface MaterialRequestCreateRequestDTO {
    id?: string;
    partCode?: string | undefined;
    requestDate?: Date;
    pONumber?: string | undefined;
    userName?: string | undefined;
    notes?: string | undefined;
    stage?: string | undefined;
    guidId?: string;
}

export interface MaterialRequestResponseDTO {
    value?: any | undefined;
}

export interface MaterialRequestUpdateRequestDTO {
    id?: string;
    partCode?: string | undefined;
    requestDate?: Date;
    pONumber?: string | undefined;
    userName?: string | undefined;
    notes?: string | undefined;
    stage?: string | undefined;
    guidId?: string;
}



//Note the following DTOs are used in Purchasing Stages Kanban Board
//before i generated the dto , i may need to check them again
export interface PurchasingGetRequestByStage {
  Stage: string | undefined;
  DraftAssessment: boolean;
}
export interface PurchasingResponseDTO {
  rmaNumber: number;
  customerEmail: string;
  dateIssued?: Date;
  dateReceived?: Date;
  rmaProblemDescription: string;
  stage: string;
  salesPerson: string;
  companyName: string;
  contactName: string;
  street?: string;
  city?: string;
  province?: string;
  zipCode?: string;
  country?: string;
  phoneNumber?: string;
  notes: string;

  draftAssessment: boolean;
  salesOrderId?: string;
  guidId: string; // UUID string
}